# Generated by Django 4.2 on 2023-10-19 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articles',
            name='path',
            field=models.FileField(upload_to='articles'),
        ),
        migrations.AlterField(
            model_name='films',
            name='path',
            field=models.FileField(upload_to='cinema'),
        ),
    ]
