# Generated by Django 4.2 on 2023-11-13 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='genre',
            name='films',
            field=models.ManyToManyField(to='database.films'),
        ),
        migrations.AddField(
            model_name='info',
            name='age',
            field=models.IntegerField(default=0),
        ),
        migrations.DeleteModel(
            name='genre_film',
        ),
    ]
