# Generated by Django 4.2 on 2023-11-13 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0002_genre_films_info_age_delete_genre_film'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='films',
            name='id',
        ),
        migrations.AlterField(
            model_name='films',
            name='title',
            field=models.CharField(max_length=128, primary_key=True, serialize=False, unique=True),
        ),
    ]
